- name: Install shellcheck in Fedora
  become: true
  dnf:
    name:
      - ShellCheck
    state: present
  when: ansible_distribution == "Fedora"

- name: Install shellcheck in Ubuntu
  become: true
  apt:
    name:
      - shellcheck
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install shellcheck in macOS
  community.general.homebrew:
    name:
      - shellcheck
    state: present
  when: ansible_distribution == "MacOSX"
