---
- name: Download zip file containing efm-langserver binary
  unarchive:
    src: https://github.com/mattn/efm-langserver/releases/download/v{{ efm_langserver_version }}/efm-langserver_v{{ efm_langserver_version }}_darwin_amd64.zip
    dest: "~/.local/bin"
    include: efm-langserver_v{{ efm_langserver_version }}_darwin_amd64/efm-langserver
    remote_src: true
    extra_opts:
      - "-j"  # do not create any directories
