---
- name: Install efm-langserver in Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install efm-langserver in macOS
  import_tasks: macos.yml
  when: ansible_distribution == "MacOSX"

- name: Install linters and formatters with apt
  become: true
  apt:
    name:
      - shellcheck
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install linters and formatters with homebrew
  become: true
  loop:
    - shellcheck
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "MacOSX"

- name: Install linters and formatters with pip
  pip:
    name:
      - flake8
      - black
      - yamllint
      - git+https://github.com/Vimjas/vint@master
    state: present
    executable: pip3

- name: Install linters and formatters with npm
  loop:
    - eslint_d
    - prettier
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
