---
- name: Install efm-langserver
  unarchive:
    src: https://github.com/mattn/efm-langserver/releases/download/v0.0.37/efm-langserver_v0.0.37_linux_amd64.tar.gz
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
      - "efm-langserver_v0.0.37_linux_amd64/efm-langserver"

- name: Install linters and formatters in apt
  become: true
  apt:
    name:
      - shellcheck
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install linters and formatters in pip
  pip:
    name:
      - flake8
      - black
      - yamllint
      - git+https://github.com/Vimjas/vint@master
    state: present
    executable: pip3

- name: Install linters and formatters in npm
  loop:
    - eslint_d
    - prettier
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
