---
- name: Install awesome
  become: true
  apt:
    name:
      - awesome
    state: present

- name: Configure awesome as a desktop entry in LightDM
  become: true
  copy:
    src: awesome.desktop
    dest: /usr/share/xsessions/awesome.desktop
