- name: Install dunst build dependencies in Ubuntu
  become: true
  apt:
    name:
      - libdbus-1-dev
      - libx11-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
      - libglib2.0-dev
      - libpango1.0-dev
      - libgtk-3-dev
      - libxdg-basedir-dev
      - libnotify-dev
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install dunst build dependencies in Fedora
  become: true
  dnf:
    name:
      - dbus-devel
      - libX11-devel
      - libXrandr-devel
      - glib2-devel
      - pango-devel
      - gtk3-devel
      - libxdg-basedir-devel
      - libXScrnSaver-devel
      - libnotify-devel
    state: present
  when: ansible_distribution == "Fedora"

- name: Build dunst
  become: true
  community.general.make:
    chdir: deps/dunst

- name: Install dunst
  become: true
  community.general.make:
    chdir: deps/dunst
    target: install
