---
- name: Install dwm build dependencies
  become: true
  apt:
    name:
      - libimlib2-dev
    state: present

- name: Build dwm
  become: true
  become_flags: "--preserve-env=HOME"
  shell:
    cmd: make clean install
    chdir: ./suckless/dwm

- name: Configure dwm as a desktop entry in LightDM
  become: true
  copy:
    src: dwm.desktop
    dest: /usr/share/xsessions/dwm.desktop

- name: Install dwm status bar dependencies
  become: true
  apt:
    name:
      - acpi
      - lm-sensors
      - alsa-utils
    state: present
