---
- name: Install psutil
  pip:
    name:
      - psutil
    state: present

- name: Enable tap to click on touchpad
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: Show battery percentage
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: Generate gnome terminal profile with pywal colors
  vars:
    colors: "{{ lookup('file', '~/.cache/wal/gnome-terminal-profile-colors') }}"
  template:
    src: gnome-terminal-profile.j2
    dest: "/tmp/gnome-terminal-profile"

- name: Load gnome terminal profile with dconf
  command:
    cmd: "dconf load /org/gnome/terminal/legacy/profiles:/"
    stdin: "{{ lookup('file', '/tmp/gnome-terminal-profile') }}"
