---
- name: Set up Ubuntu desktop
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Set up Fedora desktop
  import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"
