---
- name: Install Node.js in Ubuntu
  import_tasks: ubuntu.yml
  vars:
    nodejs_version: "14.x"
  when: ansible_distribution == "Ubuntu"

- name: Install Node.js in Fedora
  become: true
  dnf:
    name:
      - nodejs
    state: present
  when: ansible_distribution == "Fedora"

- name: Install Node.js in macOS
  community.general.homebrew:
    name:
      - node
    state: present
  when: ansible_distribution == "MacOSX"

- name: Create npm global directory
  file:
    path: "{{ npm_config_prefix }}"
    state: directory
    mode: 0755

- name: Ensure npm global prefix is configured
  lineinfile:
    path: "{{ ansible_env.HOME }}/.npmrc"
    line: "prefix={{ npm_config_prefix }}"
    state: present
    create: true

- name: Install global packages
  loop: "{{ nodejs_npm_global_packages }}"
  community.general.npm:
    name: "{{ item }}"
    state: present
    global: true
