---
- name: Install ranger in Ubuntu
  pip:
    name:
      - ranger-fm
    state: present
    executable: pip3

- name: Set up ranger desktop entry
  copy:
    src: ranger.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/"
