---
- name: Install ueberzug in Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install ranger
  pip:
    name:
      - ranger-fm
    state: present
    executable: pip3
