---
- name: Install ueberzug build dependencies in Ubuntu
  become: true
  apt:
    name:
      - libx11-dev
      - libxext-dev
      - libxres-dev
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install ueberzug build dependencies in Fedora
  become: true
  dnf:
    name:
      - libX11-devel
      - libXext-devel
      - libXres-devel
      - python3-devel
    state: present
  when: ansible_distribution == "Fedora"

- name: Install ueberzug
  pip:
    name:
      - ueberzug
    state: present
    executable: pip3

- name: Install ranger in Ubuntu
  pip:
    name:
      - ranger-fm
    state: present
    executable: pip3

- name: Set up ranger desktop entry
  copy:
    src: ranger.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/"
