- name: Install ueberzug build dependencies
  become: true
  apt:
    name:
      - libx11-dev
      - libxext-dev
      - libxres-dev
    state: present

- name: Install ueberzug
  pip:
    name:
      - ueberzug
    state: present
    executable: pip3

- name: Install ranger in Ubuntu
  pip:
    name:
      - ranger-fm
    state: present
    executable: pip3

- name: Set up ranger desktop entry
  copy:
    src: ranger.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/"
