- name: Install ueberzug build dependencies
  become: true
  apt:
    name:
      - libx11-dev
      - libxext-dev
      - libxres-dev
    state: present

- name: Install ueberzug
  pip:
    name:
      - ueberzug
    state: present
    executable: pip3
