---
- name: Install stow in Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install stow in Fedora
  import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install stow in macOS
  import_tasks: macos.yml
  when: ansible_distribution == "MacOSX"

- name: Remove file that will conflict with Stow
  loop:
    - .bashrc
    - .profile
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent

- name: Run stow
  shell: "stow . --target {{ ansible_env.HOME }} --verbose=2"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
