version: 2

tools:
  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint --format parsable -'
    lint-formats:
      - '%f:%l:%c: [%tarning] %m'
      - '%f:%l:%c: [%trror] %m'
    lint-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck --format gcc --external-sources'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  lua-luacheck: &lua-luacheck
    lint-command: 'luacheck --no-color ${INPUT}'
    lint-formats:
      - '    %f:%l:%c: %m'
    lint-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  eslint_d: &eslint_d
    lint-command: 'eslint_d -f unix --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'
    format-command: 'eslint_d --fix-to-stdout --stdin --stdin-filename ${INPUT}'
    format-stdin: true

  prettierd: &prettierd
    format-command: 'prettierd "${INPUT}"'
    format-stdin: true
    require-marker: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.json5
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.toml
      - .prettierrc.js
      - .prettierrc.cjs
      - .prettierrc.config.js
      - .prettierrc.config.cjs

  vim-vint: &vim-vint
    lint-command: 'vint --enable-neovim --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  lua-stylua: &lua-stylua
    format-command: 'stylua -'
    format-stdin: true

languages:
  yaml:
    - <<: *yaml-yamllint

  sh:
    - <<: *sh-shellcheck

  zsh:
    - <<: *sh-shellcheck

  lua:
    - <<: *lua-luacheck
    - <<: *lua-stylua

  python:
    - <<: *python-flake8

  javascript:
    - <<: *eslint_d
    - <<: *prettierd

  typescript:
    - <<: *eslint_d
    - <<: *prettierd

  javascriptreact:
    - <<: *eslint_d
    - <<: *prettierd

  typescriptreact:
    - <<: *eslint_d
    - <<: *prettierd

  vim:
    - <<: *vim-vint
