version: 2

tools:
  yamllint: &yamllint
    lint-command: 'yamllint --format parsable -'
    lint-formats:
      - '%f:%l:%c: [%tarning] %m'
      - '%f:%l:%c: [%trror] %m'
    lint-stdin: true

  shellcheck: &shellcheck
    lint-command: 'shellcheck --format gcc --external-sources'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  prettierd: &prettierd
    format-command: 'prettierd "${INPUT}"'
    format-stdin: true
    require-marker: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.json5
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.toml
      - .prettierrc.js
      - .prettierrc.cjs
      - .prettierrc.config.js
      - .prettierrc.config.cjs

  luacheck: &luacheck
    lint-command: 'luacheck --no-color ${INPUT}'
    lint-formats:
      - '    %f:%l:%c: %m'
    lint-stdin: true

  stylua: &stylua
    format-command: 'stylua --search-parent-directories -'
    format-stdin: true

languages:
  yaml:
    - <<: *yamllint

  sh:
    - <<: *shellcheck

  zsh:
    - <<: *shellcheck

  lua:
    - <<: *luacheck
    - <<: *stylua

  javascript:
    - <<: *prettierd

  typescript:
    - <<: *prettierd

  javascriptreact:
    - <<: *prettierd

  typescriptreact:
    - <<: *prettierd
