version: 2

tools:
  yamllint: &yamllint
    lint-command: 'yamllint --format parsable -'
    lint-formats:
      - '%f:%l:%c: [%tarning] %m'
      - '%f:%l:%c: [%trror] %m'
    lint-stdin: true

  shellcheck: &shellcheck
    lint-command: 'shellcheck --format gcc --external-sources'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  luacheck: &luacheck
    lint-command: 'luacheck --no-color ${INPUT}'
    lint-formats:
      - '    %f:%l:%c: %m'
    lint-stdin: true

  eslint_d: &eslint_d
    lint-command: 'eslint_d -f unix --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c: %m'
    format-command: 'eslint_d --fix-to-stdout --stdin --stdin-filename ${INPUT}'
    format-stdin: true

  vint: &vint
    lint-command: 'vint --enable-neovim --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  stylua: &stylua
    format-command: 'stylua --search-parent-directories -'
    format-stdin: true

languages:
  yaml:
    - <<: *yamllint

  sh:
    - <<: *shellcheck

  zsh:
    - <<: *shellcheck

  lua:
    - <<: *luacheck
    - <<: *stylua

  javascript:
    - <<: *eslint_d

  typescript:
    - <<: *eslint_d

  javascriptreact:
    - <<: *eslint_d

  typescriptreact:
    - <<: *eslint_d

  astro:
    - <<: *eslint_d

  mdx:
    - <<: *eslint_d

  vim:
    - <<: *vint
