---
- name: Install pywal with pip
  pip:
    name:
      - pywal
    state: present
    executable: pip3

- name: Run pywal
  command:
    cmd: wal --theme "{{ theme }}" -o "$HOME/.config/wal/done.sh"
    creates: "{{ ansible_env.HOME }}/.cache/colors"
