---
- name: Install pywal with pip
  pip:
    name:
      - git+https://github.com/dylanaraps/pywal@236aa48e741ff8d65c4c3826db2813bf2ee6f352
    state: present
    executable: pip3

- name: Get pywal last used theme
  slurp:
    src: "{{ ansible_env.HOME }}/.cache/wal/last_used_theme"
  register: last_used_theme

- name: Run pywal
  command:
    cmd: wal --theme "{{ theme }}" -o "$HOME/.config/wal/done.sh"
  changed_when: "(last_used_theme.content | b64decode) != theme ~ '.json'"
