---
- name: Install pywal with pip
  pip:
    name:
      - git+https://github.com/dylanaraps/pywal@236aa48e741ff8d65c4c3826db2813bf2ee6f352
    state: present
    executable: pip3

- name: Run pywal
  command:
    cmd: wal --theme "{{ theme }}" -o "$HOME/.config/wal/done.sh"
    creates: "{{ ansible_env.HOME }}/.cache/colors"
