---
- name: Install Hugo in Ubuntu
  become: true
  apt:
    deb: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_extended_{{ hugo_version }}_Linux-64bit.deb"
    state: present
