---
- name: Set up RPM Fusion
  become: true
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: true

- name: Install ffmpeg-libs
  become: true
  dnf:
    name:
      - ffmpeg-libs
    state: present
