---
- name: Install flatpak in Ubuntu
  become: true
  apt:
    name:
      - flatpak
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install apps with Flatpak
  community.general.flatpak:
    name:
      - com.spotify.Client
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.chromium.Chromium
    state: present
    method: user
