- name: Install Alacritty in Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install Alacritty in macOS
  import_tasks: macos.yml
  when: ansible_distribution == "MacOSX"
