---
- name: Install nvim build dependencies in Ubuntu
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install nvim build dependencies in Fedora
  become: true
  dnf:
    name:
      - ninja-build
      - libtool
      - autoconf
      - automake
      - cmake
      - gcc
      - gcc-c++
      - make
      - pkgconfig
      - unzip
      - patch
      - gettext
      - curl
    state: present
  when: ansible_distribution == "Fedora"

- name: Check if previous build exist
  ansible.builtin.stat:
    path: deps/nvim/build
  register: nvim_build

- name: Uninstall previous installation of nvim
  become: true
  ansible.builtin.command:
    chdir: deps/nvim
    cmd: cmake --build build/ --target uninstall
  when: nvim_build.stat.exists

- name: Clean git repository
  ansible.builtin.command:
    chdir: deps/nvim
    cmd: git clean -fdx
  changed_when: false

- name: Clean previous nvim builds
  community.general.make:
    chdir: deps/nvim
    target: clean
  changed_when: false

- name: Build nvim release version in Linux
  community.general.make:
    chdir: deps/nvim
    params:
      CMAKE_BUILD_TYPE: Release

- name: Install nvim release version in Linux
  become: true
  community.general.make:
    chdir: deps/nvim
    target: install
