---
- name: Install nvim build dependencies in Ubuntu
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install nvim build dependencies
  become: true
  dnf:
    name:
      - gcc-g++
      - ninja-build
      - libtool
      - autoconf
      - automake
      - cmake
      - gcc
      - gcc-c++
      - make
      - pkgconfig
      - unzip
      - patch
      - gettext
      - curl
    state: present
  when: ansible_distribution == "Fedora"

- name: Build nvim release version in Ubuntu
  community.general.make:
    chdir: deps/neovim
    params:
      CMAKE_BUILD_TYPE: Release

- name: Install nvim release version in Ubuntu
  become: true
  community.general.make:
    chdir: deps/neovim
    target: install
