---
- name: Set fonts installation path as Ansible fact in Linux
  set_fact:
    fonts_path: "{{ ansible_env.HOME }}/.local/share/fonts"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Fedora"

- name: Set fonts installation path as Ansible fact in macOS
  set_fact:
    fonts_path: "{{ ansible_env.HOME }}/Library/Fonts"
  when: ansible_distribution == "MacOSX"

- name: Create fonts directory
  file:
    path: "{{ fonts_path }}"
    state: directory
    mode: "0775"

- name: Install Source Code Pro
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/blob/29fdb884c6e9dc2a312f4a5e2bb3b2dad2350777/TTF/SourceCodePro-Medium.ttf?raw=true
    dest: "{{ fonts_path }}/SourceCodePro-Medium.ttf"
