---
- name: Install git-delta in Ubuntu
  become: true
  apt:
    deb: "https://github.com/dandavison/delta/releases/download/{{ git_delta_version }}/git-delta_{{ git_delta_version }}_amd64.deb"
  when: ansible_distribution == "Ubuntu"
