---
- name: Install efm-langserver in Linux
  unarchive:
    src: https://github.com/mattn/efm-langserver/releases/download/v{{ efm_langserver_version }}/efm-langserver_v{{ efm_langserver_version }}_linux_amd64.tar.gz
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
      - "efm-langserver_v{{ efm_langserver_version }}_linux_amd64/efm-langserver"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Fedora"

- name: Install efm-langserver in macOS
  unarchive:
    src: https://github.com/mattn/efm-langserver/releases/download/v{{ efm_langserver_version }}/efm-langserver_v{{ efm_langserver_version }}_darwin_amd64.zip
    dest: "~/.local/bin"
    include: efm-langserver_v{{ efm_langserver_version }}_darwin_amd64/efm-langserver
    remote_src: true
    extra_opts:
      - "-j"  # do not create any directories
  when: ansible_distribution == "MacOSX"

- name: Install linters and formatters with dnf
  become: true
  dnf:
    name:
      - ShellCheck
    state: present
  when: ansible_distribution == "Fedora"

- name: Install linters and formatters with apt
  become: true
  apt:
    name:
      - shellcheck
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install linters and formatters with homebrew
  loop:
    - shellcheck
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "MacOSX"

- name: Install linters and formatters with pip
  ansible.builtin.pip:
    name:
      - flake8
      - black
      - yamllint
      - git+https://github.com/Vimjas/vint@master
    state: present
    executable: pip3

- name: Install linters and formatters with npm
  loop:
    - eslint_d
    - prettier
    - "@tailwindcss/language-server"
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present

- name: Install unzip in Ubuntu
  become: true
  ansible.builtin.apt:
    name:
      - unzip
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install stylua from GitHub releases
  unarchive:
    src: "https://github.com/JohnnyMorganz/StyLua/releases/download/v0.13.1/stylua-{{ 'macos' if ansible_facts['os_family'] == 'Darwin' else 'linux' }}.zip"
    dest: "~/.local/bin"
    mode: "u+x"
    remote_src: true
