---
- name: Install CLI tools in Ubuntu
  become: true
  apt:
    name:
      - tig
      - tmux
      - ripgrep
      - fd-find
      - jq
      - htop
      - python3-pip
      - pass
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install CLI tools in Fedora
  become: true
  dnf:
    name:
      - tig
      - tmux
      - ripgrep
      - fd-find
      - jq
      - htop
      - python3-pip
      - pass
    state: present
  when: ansible_distribution == "Fedora"

- name: Install CLI tools in macOS with Homebrew
  loop:
    - tig
    - tmux
    - ripgrep
    - fd
    - jq
    - htop
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "MacOSX"
