---
- name: Install CLI tools in Ubuntu
  become: true
  apt:
    name:
      - tig
      - tmux
      - ripgrep
      - fd-find
      - jq
      - htop
      - python3-pip
      - pass
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install git-delta in Ubuntu
  become: true
  apt:
    deb: "https://github.com/dandavison/delta/releases/download/{{ git_delta_version }}/git-delta_{{ git_delta_version }}_amd64.deb"
  vars:
    git_delta_version: 0.13.0
  when: ansible_distribution == "Ubuntu"

- name: Install CLI tools in Fedora
  become: true
  dnf:
    name:
      - tig
      - tmux
      - ripgrep
      - fd-find
      - jq
      - htop
      - python3-pip
      - pass
      - git-delta
    state: present
  when: ansible_distribution == "Fedora"

- name: Install CLI tools in macOS
  loop:
    - tig
    - tmux
    - ripgrep
    - fd
    - jq
    - htop
    - git-delta
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "MacOSX"

- name: Install diffstatic
  import_tasks: diffstatic.yml
  vars:
    diffstatic_version: 0.35.0

- name: Install GitHub CLI
  import_tasks: github-cli.yml
  vars:
    github_cli_version: 2.15.0
