- name: Install tokei in Fedora
  become: true
  dnf:
    name:
      - tokei
    state: present
  when: ansible_distribution == "Fedora"

- name: Install tokei in Ubuntu
  unarchive:
    src: https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    include:
      - tokei
    extra_opts:
      - "-z"
  when: ansible_distribution == "Ubuntu"

- name: Install tokei in macOS
  community.general.homebrew:
    name:
     - tokei
    state: present
  when: ansible_distribution == "MacOSX"
